# Generated by Django 6.0.1 on 2026-02-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espana_es', '0006_evenetrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvenetRating',
            new_name='EventRating',
        )
    ]
